---
#-------------------------------
# General Site Settings

titulo: 36 Encuentro Plurinacional <br>de Mujeres y Disidencias 

logo: logo_blanco2.png
author: Desarrollado por 36° Encuentro Plurinacional de Mujeres y Disidencias - Bariloche/Furilofche
description: Pagina del 36 encuentro plurinaciones de mujeres y disidencias
email: 36encuentropluri.info@gmail.com
#phone: +880 2544 658 256
#address:  USA
#copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: Qué es, link: "/quees" }
  - { name: Por qué, link: "/porque" }
  - { name: Cronograma, link: "/cronograma" }
  - { name: Talleres, link: "/talleres" }
  - { name: Logística, link: "/logistica" }
  - { name: Contacto, link: "/contacto" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Main Section

main:
  main-titulo: 36° Encuentro Plurinacional de Mujeres, Lesbianas, Travestis, Trans, Bisexuales, Intersexuales </br> y No Binaries </br>
  main-subtitulo: 14, 15 y 16 de  octubre 2023 </br> Bariloche - Furilofche
  main-button-texto: ¿QUÉ ES?
  main-button-url: "/quees"
  main-button-texto-2: VER CRONOGRAMA
  main-button-url-2: "/cronograma"

  social:
  - { icon: "ti-facebook", link: "https://www.facebook.com/p/36-Encuentro-Plurinacional-de-mujeres-y-disidencias-2023-100088135622331/" }
  - { icon: "ti-instagram", link: "https://www.instagram.com/36encpluri.mujeresydisidencias/?hl=es-la" }
  
#-------------------------------
# Porque (Section and Page)
porque-titulo: ¿Por qué en Bariloche?
porque-contenido: La indignación colectiva del movimiento de mujeres y disidencias frente al violento desalojo de la comunidad Lafken Winkul Mapu en el cual fueron detenidas siete mujeres mapuche junto a sus niñes, por causas excarcelables, impulsó la elección de Bariloche como sede en los dos encuentros realizados en San Luis en 2022, el de octubre y el de noviembre.<br/><br/>Esta situación particular y la de todas las mujeres y disidencias indígenas, en conflicto territorial será parte de la agenda de los feminismos durante los tres días del Encuentro.
porque-button-texto: LEER MÁS
porque-button-url: "/porque"

#-------------------------------
# Talleres y Actividades (Section and Page)
actividades:
  actividades-titulo: Talleres
  actividades-contenido: Los talleres son el corazón de los encuentros. Históricamente se conforman por las y les participantes del encuentro, son democráticos, horizontales y pluralistas. Todas y todes pueden sumarse, opinar y problematizar aquellas prácticas que nos resultan injustas y en las que nos vemos inmersas/es a diario. 
  actividades-button-texto: VER MÁS
  actividades-button-url: "/talleres"

#-------------------------------
# Logistica (Section and Page)
logistica:
  logistica-titulo: Alojamiento, Transporte e Información útil
logistica-sections:
  - {
      titulo: Certificado Asistencia,
      icon: certificado.png,
      descripcion: "Descargá el certificado de participación en el Encuentro.",
      button-texto: DESCARGAR,
      button-url: "/assets/docs/certificado_de_asistencia.pdf",
    }
  - {
      titulo: Alojamiento,
      icon: alojamiento.png,
      descripcion: "Diversas opciones de alojamiento en la ciudad.",
      button-texto: VER MÁS,
      button-url: /logistica#logistica_alojamiento,
    }
  - {
      titulo: Transporte,
      icon: transporte.png,
      descripcion: "Medios de transporte disponibles.<br/><br/>" ,
      button-texto: VER MÁS,
      button-url: /logistica#logistica_transporte,
    }

logistica-alojamientos-privados:
  - {
      nombre: Bariloche turismo,
      url: "https://barilocheturismo.gob.ar/es/buscar-hotel",
    }
  - {
      nombre: Bariloche.org,
      url: "https://bariloche.org/directorio/categorias/alojamiento-en-bariloche",
    }
  - {
      nombre: Mercado Libre,
      url: "https://listado.mercadolibre.com.ar/alojamiento-en-bariloche",
    }
  - {
      nombre: Google,
      url: "https://www.google.com.ar/travel/search?qs=CAE4BA&utm_campaign=sharing&utm_medium=link&utm_source=htls&ts=CAEaOAoaEhgKCy9nLzEyMHF3YjZnOglCYXJpbG9jaGUSGhIUCgcI5w8QChgZEgcI5w8QChgaGAEyAhAAKgcKBToDQVJT&sa=X&ap=MAE&ved=0CAAQ5JsGahcKEwiYsPLwsdaBAxUAAAAAHQAAAAAQCw",
    }
  - {
      nombre: Airbnb,
      url: "https://www.airbnb.com.ar/s/Bariloche/homes?adults=2",
    }
  - {
      nombre: Despegar,
      url: "https://www.despegar.com.ar/hoteles/hl/901/i1/hoteles-en-san+carlos+de+bariloche",
    }

logistica-transportes:
  - {
      nombre: Mi Bus,
      url: "https://mibus.com.ar/bariloche/",
    }
  - {
      nombre: Línea 33 empresa “Las Grutas”,
      url: "https://www.municipiodinahuapi.gob.ar/?q=content/horario-l%C3%ADnea-33",
    }

#-------------------------------
# Varios Section

varios: 
varios-sections:
  - {
      titulo: Inscripciones,
      icon: inscripciones.png,
      descripcion: "La inscripción no es obligatoria. <br/>Podés participar de todo sin restricciones. <br/>Sin embargo, tu aporte económico sirve para garantizar la realización de este encuentro.<br/> ¡Es muy valioso que te sumes a la inscripción!<br/>",
      button-url: https://forms.gle/Erphmr4xAuQVizqh9,
      button-texto: "VER MÁS",
      activo: ,# Add true to select section
    }
  - {
      titulo: Aportes,
      icon: aportes.png,
      descripcion: "Los encuentros son autónomos y autofinanciados. No se aceptan contribuciones que impliquen condicionamientos. La construcción la hacemos entre todas y todes, si querés aportar podes hacerlo directamente a la cuenta de la comisión organizadora. ¡Gracias!",
      button-url: assets/docs/aportes.pdf,
      button-texto: "VER MÁS",
      activo: , # Add true to select section
    }
  
#-------------------------------
# Contact Section

contactos-titulo: Contactos
contactos-1:
  - {
      nombre: Subcomisión de Accesibilidad,
      mail: comision.accesibilidad.36@gmail.com
    }
  - {
      nombre: Subcomisión de Articulación,
      mail: articulación36encuentro@gmail.com
    }
  - {
      nombre: Subcomisión de Cultura,
      mail: 36encuentropluri.cultura@gmail.com
    }
  - {
      nombre: Subcomisión de Talleres,
      mail: 36encuentropluri.talleres@gmail.com
    }
  - {
      nombre: Subcomisión de Prensa,
      mail: 36encuentroplurinacional@gmail.com
    }
contactos-2:
  - {
      nombre: Subcomisión de Finanzas,
      mail: 36encuentropluri.finanzas@gmail.com
    }
  - {
      nombre: Subcomisión de Alojamiento,
      mail: 36encuentropluri.alojamiento@gmail.com
    }
  - {
      nombre: Subcomisión de Logistica,
      mail: 36encuentropluri.logistica@gmail.com
    }
  - {
      nombre: Subcomisión de Feria,
      mail: 36encuentropluri.feria@gmail.com
    }
  - {
      nombre: Subcomisión de Sustentabilidad,
      mail: 36encuentropluri.sustentabilidad@gmail.com
    }

  
  
#-------------------------------
# Prensa 
prensa-titulo: Prensa Colaborativa
prensa-contenido: Si querés acreditarte para realizar la cobertura periodística colaborativa del 36 encuentro, completá el formulario.  
prensa-button-texto: FORMULARIO
prensa-button-url: "https://forms.gle/L9i1YU6BwC93dcKZ7"

#-------------------------------
# Application 
app-titulo: ¡App del Encuentro!
app-contenido: Si tenés un teléfono con Android podés descargar la app para tener a mano el cronograma de actividades y talleres con sus ubicaciones.<br/><br/>También podés ver en tiempo real cómo viajan las expresiones de apoyo que mandás por la app. 
app-button-1-texto: Descargala
app-button-1-url: https://play.google.com/store/apps/details?id=com.encuentro2023animus.app
app-button-2-texto: Ver Expresiones
app-button-2-url: https://ahora.encuentroplurimujeresydisidencias.com.ar/



# Que es Section
quees-pilares:
quees-pilares-titulo: "Su éxito y crecimiento se basa en los siguientes pilares que los caracterizan:" 

quees-pilares-sections:
  - titulo: "Autoconvocados"
    icon: "purple_autoconvocados.png"
    contenido: "Cada año, en el lugar elegido como sede,  se auto convocan todas y todes las y les  que lo deseen para conformar la  Comisión Organizadora, desde donde  participan a título individual. La comisión organizadora se ocupa de organizar el  encuentro y las decisiones se toman por consenso."

  - titulo: "Autónomos y autofinanciados"
    icon: "purple_autonomo.png"
    contenido: "La decisión de crear un espacio  independiente va de la mano de no  aceptar ninguna contribución económica  que implique condicionamientos. Nadie  por fuera de la comisión organizadora  puede influir y direccionar los Encuentros."

  - titulo: "Plurales"
    icon: "purple_plurales.png"
    contenido: "Implica la multiplicación de participantes  que garantizan la abierta conformación  de las comisiones organizadoras en cada  lugar y a su vez la amplia participación  sin restricciones de las mujeres, lesbianas, travestis, trans bisexuales, intersexuales, y no binaries."

  - titulo: "Plurinacionales"
    icon: "purple_plurinacionales.png"
    contenido: "En los encuentros participamos  identidades de distintos orígenes étnico  raciales, migrantes y de los pueblos  originarios."
  
  - titulo: "Federales"
    icon: "purple_federales.png"
    contenido: "Se abren a su realización en todas las  provincias del país. Amplía no  sólo la cantidad, sino también la calidad  de la participación de las mujeres y  disidencias a lo largo y ancho del país."

  - titulo: "Democráticos y horizontales"
    icon: "purple_democraticos.png"
    contenido: "Todas y todes pueden hacer oír su voz.  No existen estructuras jerárquicas ni referentes. Ningune tiene la palabra por encima de les otres. Los encuentros no emiten resoluciones, sino conclusiones propias de cada taller de debate y no del conjunto del encuentro."

quees-podcasts-titulo: Voces Encuentreras
quees-podcasts-descripcion: Un podcast del 36 Encuentro Plurinacional de Mujeres, Lesbianas, Travestis, Trans, Bisexuales, Intersexuales y No Binaries.
  
quees-podcasts:
  - nombre: "Voces Encuentreras N°1"
    file: "N1_VOCES_ENCUENTRERAS.mp3"

  - nombre: "Voces Encuentreras N°2"
    file: "N2_VOCES_ENCUENTRERAS.mp3"

  - nombre: "Voces Encuentreras N°3"
    file: "N3_VOCES_ENCUENTRERAS.mp3"

  - nombre: "Voces Encuentreras N°4"
    file: "N4_VOCES_ENCUENTRERAS.mp3"

talleres-conclusiones-titulo: Conclusiones 
talleres-conclusiones-descripcion: Las conclusiones construidas a partir de los talleres de años anteriores

talleres-conclusiones:
    - nombre: "35° Encuentro - San Luis - Territorio Huarpe, Comechingon y Ranquel"
      archivo: "Conclusiones_Talleres_35_EPMLTTBINB.pdf"
